--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cosmicnebula200/ReferMeBro
build-by-default: true
branches:
- main
projects:
  ReferMeBro:
    path: ""
    libs:
      - src: ACM-Pocketmine-MP/CortexPE/Commando
        version:  ^3.2.1
      - src: poggit/libasynql/libasynql
        version: ^4.2.0
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.3
        branch: pm5
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
...
